backports/muacme: replace dependency cmd:openssl with openssl
ERROR: unsatisfiable constraints:
  cmd:openssl (virtual):
    provided by: openssl libressl
    required by: muacme-0.1.1-r0[cmd:openssl]