user/mastodon: fix broken streaming due to missing dependency
    node:internal/modules/cjs/loader:1147
      throw err;
      ^

    Error: Cannot find module 'string-width'
    Require stack:
    - /usr/lib/mastodon/streaming/node_modules/wide-align/align.js
    - /usr/lib/mastodon/streaming/node_modules/gauge/lib/render-template.js
    - /usr/lib/mastodon/streaming/node_modules/gauge/lib/plumbing.js
    - /usr/lib/mastodon/streaming/node_modules/gauge/lib/index.js
    - /usr/lib/mastodon/streaming/node_modules/npmlog/lib/log.js
    - /usr/lib/mastodon/streaming/index.js
        at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
        at Module._load (node:internal/modules/cjs/loader:985:27)
        at Module.require (node:internal/modules/cjs/loader:1235:19)
        at require (node:internal/modules/helpers:176:18)
        at Object.<anonymous> (/usr/lib/mastodon/streaming/node_modules/wide-align/align.js:2:19)
        at Module._compile (node:internal/modules/cjs/loader:1376:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
        at Module.load (node:internal/modules/cjs/loader:1207:32)
        at Module._load (node:internal/modules/cjs/loader:1023:12)
        at Module.require (node:internal/modules/cjs/loader:1235:19) {
      code: 'MODULE_NOT_FOUND',
      requireStack: [
        '/usr/lib/mastodon/streaming/node_modules/wide-align/align.js',
        '/usr/lib/mastodon/streaming/node_modules/gauge/lib/render-template.js',
        '/usr/lib/mastodon/streaming/node_modules/gauge/lib/plumbing.js',
        '/usr/lib/mastodon/streaming/node_modules/gauge/lib/index.js',
        '/usr/lib/mastodon/streaming/node_modules/npmlog/lib/log.js',
        '/usr/lib/mastodon/streaming/index.js'
      ]
    }